#FROM golang:1.18-bullseye AS build
FROM golang:latest AS build

WORKDIR /build
COPY . .

#RUN go get go@1.18
RUN go mod download
RUN go mod verify

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /main .


FROM scratch
COPY --from=build /main .

ENTRYPOINT ["./main"]